a=int(input("enter first number="))
b=int(input("enter secound number="))
print("sum.",a+b)
print("sub.",a-b)
print("mul.",a*b)
print("dev",a/b)
print("in.de.",a//b)
print("exp.",a**b)
print("mod.",a%b)